# apiVersion: extensions/v1beta1
# kind: Deployment
# metadata:
#   name: hellowhale
# spec:
#   replicas: 1
#   template:
#     metadata:
#       labels:
#         name: hellowhale
#         hellowhale: "true"
#         role: db
#     spec:
#       containers:
#         - image: mouhamedfall/hellowhale
#           #imagePullPolicy: Always
#           name: hellowhale
#           # resources:
#           #   # keep request = limit to keep this container in guaranteed class
#           #   limits:
#           #     cpu: 100m
#           #     memory: 200Mi
#           #   requests:
#           #     cpu: 100m
#           #     memory: 200Mi
#           ports:
#             - containerPort: 81



kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: hellowhale
  labels:
    name: hellowhale
    app: hellowhale
  #namespace: kube-system
spec:
  replicas: 1
  #replicas: 1
  selector:
    matchLabels:
      name: hellowhale
      app: hellowhale
  template:
    metadata:
      labels:
        name: hellowhale
        app: hellowhale
    spec:
      containers:
      - name: hellowhale 
        image: mouhamedfall/hellowhale:12
        imagePullPolicy: Never
        ports:
        - containerPort: 8181
          name: hellowhale
