---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  type: NodePort
  ports:
    - port: 80
      #targetPort: 31537
      nodePort: 31537
      protocol: TCP
      name: nginx
  selector:
    app: nginx
